-- config built on top of https://github.com/josean-dev/dev-environment-files
require("tynasello.plugins-setup")
require("tynasello.core.options")
require("tynasello.core.keymaps")
require("tynasello.core.colorscheme")
require("tynasello.plugins.comment")
require("tynasello.plugins.nvim-tree")
require("tynasello.plugins.lualine")
require("tynasello.plugins.telescope")
require("tynasello.plugins.nvim-cmp")
require("tynasello.plugins.lsp.mason")
require("tynasello.plugins.lsp.lspsaga")
require("tynasello.plugins.lsp.lspconfig")
require("tynasello.plugins.lsp.null-ls")
require("tynasello.plugins.autopairs")
require("tynasello.plugins.treesitter")
require("tynasello.plugins.gitsigns")
